"""Type stubs for syma_py native module."""

from typing import Any, Dict, List, Optional, Union

SymaValueInt = int
SymaValueReal = float
SymaValueStr = str
SymaValueBool = bool
SymaValueList = list
SymaValueDict = dict
SymaNative = Union[SymaValueInt, SymaValueReal, SymaValueStr, SymaValueBool, SymaValueList, SymaValueDict, None]


class SymaValue:
    """Wrapper for Syma values without a native Python equivalent."""

    type_tag: str
    display: str

    def __init__(self) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def to_python(self) -> Any: ...
    def to_json(self) -> Dict[str, Any]: ...
    @property
    def value(self) -> Any: ...
    def to_expr(self) -> str: ...


class SymaKernel:
    """Syma evaluation engine — holds state across calls."""

    def __init__(self) -> None: ...
    def eval(self, code: str) -> Union[SymaNative, SymaValue]: ...
    def eval_raw(self, code: str) -> Union[SymaNative, SymaValue]: ...
    def eval_detailed(self, code: str) -> Dict[str, Any]: ...
    def eval_many(self, code: str) -> List[Union[SymaNative, SymaValue]]: ...
    def get(self, name: str) -> Optional[Union[SymaNative, SymaValue]]: ...
    def set(self, name: str, value: Any) -> None: ...
    def bindings(self) -> Dict[str, Any]: ...
    def reset(self) -> None: ...
    def __enter__(self) -> "SymaKernel": ...
    def __exit__(
        self,
        exc_type: Any,
        exc_val: Any,
        exc_tb: Any,
    ) -> None: ...


class SymaParseError(ValueError): ...
class SymaEvalError(RuntimeError): ...
class SymaLexError(ValueError): ...
